name: Windows Release
permissions:
  contents: write

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          .\vcpkg\bootstrap-vcpkg.bat

      - name: Install cURL via vcpkg
        run: |
          .\vcpkg\vcpkg install curl
          .\vcpkg\vcpkg integrate install
          
      - name: Configure
        run: cmake . -D CMAKE_TOOLCHAIN_FILE=.\vcpkg\scripts\buildsystems\vcpkg.cmake -D CMAKE_BUILD_TYPE=Release -D BUILD_EXAMPLES=OFF

      - name: Package source code
        run: cmake --build . --target ALL_BUILD --config Release

      - name: Create windows directory
        run: cmake -E make_directory windows

      - name: Copy include directory
        run: cmake -E copy_directory include windows/include

      - name: Copy .lib file
        run: cmake -E copy lib/Release/tsar.lib windows/tsar.lib

      - name: Create zip archive
        run: cmake -E tar cfz windows.zip --format=zip windows

      - name: Add packaged code to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: windows.zip
          tag: ${{ github.ref }}
