name: Windows Release
permissions:
  contents: write

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configure
        run: cmake . -D CMAKE_BUILD_TYPE=Release -D BUILD_EXAMPLES=OFF
      - name: Package source code
        run: cmake --build . --target ALL_BUILD

      - name: Add packaged source code to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/tsar-src.zip
          tag: ${{ github.ref }}
